# Generated by Django 5.0.3 on 2024-03-19 10:20

import django.db.models.deletion
import survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surveys/images/')),
                ('music_file_1', models.FileField(blank=True, null=True, upload_to='surveys/music/')),
                ('music_file_2', models.FileField(blank=True, null=True, upload_to='surveys/music/')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_music', models.IntegerField(choices=[(1, 'Music 1'), (2, 'Music 2')], null=True, validators=[survey.models.validate_preferred_music])),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
