# Generated by Django 5.0.3 on 2024-03-19 09:08

import survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='option_one',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='preferred_music',
            field=models.IntegerField(choices=[(1, 'Music 1'), (2, 'Music 2')], null=True, validators=[survey.models.validate_preferred_music]),
        ),
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surveys/images/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='music_file_1',
            field=models.FileField(blank=True, null=True, upload_to='surveys/music/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='music_file_2',
            field=models.FileField(blank=True, null=True, upload_to='surveys/music/'),
        ),
    ]
