# Generated by Django 5.0.3 on 2024-04-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_demographic_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(default='demographic', max_length=30),
        ),
    ]
